
spring:
  datasource:
    url: jdbc:h2:mem:msgdb
    driverClassName: org.h2.Driver
    username: mmutawe
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
#      settings.trace: false


